import React,{useRef,useState} from 'react';
import {SERVICES} from '../../data/servicesData';
import {quotesApi} from '../../services/api';
import useDialog from '../../hooks/useDialog';
export default function QuoteWizardModal({onClose,initialService=''}){
 const ref=useRef(null),[service,setService]=useState(initialService),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
 const [form,setForm]=useState({name:'',email:'',phone:'',timeline:'Flexible / next available',details:''});
 useDialog(ref,onClose);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const s=SERVICES.find(x=>x.title===service);const r=await quotesApi.submitPublicQuote({...form,id:'MM-'+crypto.randomUUID(),serviceCategory:s?.category||'Consultation',detailedService:service||'General consultation',make:'PMU Consultation',modelAndYear:'',location:'Folsom'});if(!r.success||!r.quoteId)throw new Error();setSent(true);}catch{setError('Your request could not be sent. Please try again, or call (916) 542-8801.');}finally{setBusy(false);}};
 return <div className="mm-modal-backdrop"><section className="mm-booking" ref={ref} role="dialog" aria-modal="true" aria-labelledby="booking-title"><header><span className="mm-kicker">THE MAKEOVER MOMMY / LET’S CONNECT</span><button onClick={onClose}>Close ×</button></header>{sent?<div className="mm-booking-body mm-booking-success" role="status"><p className="mm-kicker">YOUR REQUEST IS WITH US</p><h2 id="booking-title">A beautiful<br/><em>beginning.</em></h2><p>Thank you, {form.name}. The studio will contact you to discuss your treatment and arrange a time.</p><p>This is a consultation request. Your appointment is confirmed personally by the studio.</p><button className="mm-cta" onClick={onClose}>Back to exploring ↗</button></div>:<form className="mm-booking-body mm-fields" onSubmit={submit}><h2 id="booking-title">Let’s start<br/><em>with you.</em></h2><p>Tell us a little about what you have in mind. Porsche will help with the next step.</p><label>Treatment<select value={service} onChange={e=>setService(e.target.value)}><option value="">Help me choose / general consultation</option>{SERVICES.map(s=><option key={s.id}>{s.title}</option>)}</select></label><label>Your name<input name="name" autoComplete="name" required value={form.name} onChange={change}/></label><div className="mm-field-pair"><label>Email<input name="email" type="email" autoComplete="email" required value={form.email} onChange={change}/></label><label>Phone<input name="phone" type="tel" autoComplete="tel" required value={form.phone} onChange={change}/></label></div><label>Preferred timing<select name="timeline" value={form.timeline} onChange={change}><option>Flexible / next available</option><option>Tuesday–Friday / morning</option><option>Tuesday–Friday / afternoon</option><option>Saturday / by appointment</option></select></label><label>Anything you’d like us to know? <small>Optional — please leave medical details for your consultation.</small><textarea rows={2} name="details" value={form.details} onChange={change}/></label>{error&&<p className="mm-error" role="alert">{error}</p>}<button className="mm-cta" disabled={busy}>{busy?'Sending your request…':'Request a consultation'}<span aria-hidden="true">↗</span></button><small>No payment is taken here. The studio will contact you to confirm availability.</small></form>}</section></div>;
}
