import React, { useState, useEffect } from 'react';
import { settingsApi, authApi } from '../../services/api';
export default function AdminSettings(){
 const [settings,setSettings]=useState(null),[tab,setTab]=useState('studio'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[passwords,setPasswords]=useState({old:'',next:'',confirm:''}),[testEmail,setTestEmail]=useState('');
 const load=async()=>{setError('');try{const s=await settingsApi.getSettings();setSettings(s);setTestEmail(s.shop_email||'');}catch{setError('Studio settings could not be loaded.');}};
 useEffect(()=>{load();},[]);
 const field=(key,label,type='text')=><label key={key}>{label}<input type={type} value={settings[key]||''} onChange={e=>setSettings(s=>({...s,[key]:e.target.value}))}/></label>;
 const act=async task=>{setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(e.message||'This change could not be completed.');}finally{setBusy(false);}};
 const save=e=>{e.preventDefault();act(async()=>{const r=await settingsApi.saveSettings(settings);if(!r.success)throw new Error('Settings could not be saved.');setSettings(r.settings);setNotice('Your studio settings have been saved.');});};
 const password=e=>{e.preventDefault();if(passwords.next!==passwords.confirm){setError('The new passwords do not match.');return;}act(async()=>{await authApi.changePassword(passwords.old,passwords.next);setPasswords({old:'',next:'',confirm:''});setNotice('Your password has been updated.');});};
 return <section className="mm-admin-panel mm-settings"><div className="mm-tabs">{[['studio','Studio details'],['email','Email'],['alerts','Notifications'],['access','Access']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setError('');setNotice('');}}>{label}</button>)}</div>
 {error&&<p className="mm-error" role="alert">{error} {!settings&&<button onClick={load}>Retry</button>}</p>}{notice&&<p className="mm-success" role="status">{notice}</p>}
 {!settings?<p className="mm-admin-empty">{error?'Reconnect to load your settings.':'Loading studio settings…'}</p>:tab==='access'?<form className="mm-settings-form" onSubmit={password}><h2>Studio access</h2><p>Update the password used to enter your workspace.</p>{[['old','Current password','current-password'],['next','New password','new-password'],['confirm','Confirm new password','new-password']].map(([key,label,auto])=><label key={key}>{label}<input type="password" autoComplete={auto} required minLength={key==='old'?1:6} value={passwords[key]} onChange={e=>setPasswords(p=>({...p,[key]:e.target.value}))}/></label>)}<button className="mm-button" disabled={busy}>{busy?'Updating…':'Update password ↗'}</button></form>:<form className="mm-settings-form" onSubmit={save}>
 {tab==='studio'&&<><h2>The studio details</h2><p>Contact information and defaults used in client communications.</p><div className="mm-field-pair">{field('shop_phone','Studio phone','tel')}{field('shop_email','Studio email','email')}</div>{field('shop_address','Studio address')}{field('default_warranty','Default aftercare or service note')}<label>Default estimate notes<textarea rows={3} value={settings.default_quote_notes||''} onChange={e=>setSettings(s=>({...s,default_quote_notes:e.target.value}))}/></label></>}
 {tab==='email'&&<><h2>Client email</h2><p>Connect the studio's EmailJS account for estimates and notifications.</p><div className="mm-field-pair">{field('emailjs_service_id','Service ID')}{field('emailjs_public_key','Public key')}{field('emailjs_template_id_quote','Client estimate template')}{field('emailjs_template_id_notify','Studio notification template')}</div><div className="mm-settings-test"><label>Test recipient<input type="email" value={testEmail} onChange={e=>setTestEmail(e.target.value)}/></label><button type="button" className="mm-text-link" disabled={busy||!testEmail} onClick={()=>act(async()=>{const r=await settingsApi.testEmail({toEmail:testEmail,serviceId:settings.emailjs_service_id,templateId:settings.emailjs_template_id_quote,publicKey:settings.emailjs_public_key});if(!r.success)throw new Error(r.error||'Test email failed.');setNotice(r.message||'Test email sent.');})}>Send a test email ↗</button></div></>}
 {tab==='alerts'&&<><h2>Studio notifications</h2><p>Receive new consultation alerts in your connected Telegram chat.</p><label className="mm-checkbox"><input type="checkbox" checked={!!settings.telegram_enabled} onChange={e=>setSettings(s=>({...s,telegram_enabled:e.target.checked}))}/>Enable Telegram alerts</label>{field('telegram_bot_token','Bot token','password')}{field('telegram_chat_id','Chat ID')}<button className="mm-text-link" type="button" disabled={busy||!settings.telegram_bot_token||!settings.telegram_chat_id} onClick={()=>act(async()=>{const r=await settingsApi.testTelegram(settings.telegram_bot_token,settings.telegram_chat_id);if(!r.success)throw new Error(r.error||'Connection test failed.');setNotice(r.message||'Test notification sent.');})}>Send a test notification ↗</button></>}
 <div className="mm-settings-save"><button className="mm-button" disabled={busy}>{busy?'Working…':'Save settings ↗'}</button></div>
 </form>}
 </section>;
}
