import React, { useState, useEffect } from 'react';
import { quotesApi } from '../../services/api';
import { Status } from './DashboardOverview';
const clientText = text => (text || '').replace(/^Vehicle:/gm, 'Consultation:').replace(/^Symptoms & Details:/gm, 'Client notes:');
export default function InboxView({ onOpenFullQuote, revision }) {
 const [threads,setThreads]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[search,setSearch]=useState(''),[reply,setReply]=useState(''),[price,setPrice]=useState(''),[attach,setAttach]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[messageLoading,setMessageLoading]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{let live=true;setLoading(true);quotesApi.getInbox().then(r=>{if(live){setThreads(r.threads||[]);setSelected(previous=>previous?(r.threads||[]).find(t=>t.id===previous.id)||null:null);setError('');}}).catch(()=>{if(live)setError('Unable to load client messages. Please retry.');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[revision,reload]);
 useEffect(()=>{if(!selected)return;let live=true;setMessages([]);setMessageLoading(true);setReply('');setPrice('');setAttach(false);setError('');quotesApi.getMessages(selected.id).then(r=>{if(live)setMessages(r.messages||[]);}).catch(()=>{if(live)setError('Unable to load this conversation.');}).finally(()=>{if(live)setMessageLoading(false);});return()=>{live=false;};},[selected?.id,reload]);
 const send=async e=>{e.preventDefault();if(busy||!reply.trim())return;setBusy(true);setError('');try{const r=await quotesApi.sendMessage(selected.id,{message:reply.trim(),quotePrice:attach&&price?price:null});if(!r.message)throw new Error();setMessages(m=>[...m,r.message]);setReply('');setPrice('');setAttach(false);if(!r.emailDelivery?.success)setError('Reply saved in the studio. Email delivery is unavailable; contact the client directly.');}catch{setError('Your message was not sent. Please try again.');}finally{setBusy(false);}};
 const filtered=threads.filter(t=>((t.name||'')+' '+(t.detailedService||'')+' '+(t.email||'')).toLowerCase().includes(search.toLowerCase()));
 return <><div className="mm-inbox mm-admin-panel" data-selected={!!selected}>
 <aside className="mm-inbox-list"><label className="mm-search">Find a conversation<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search clients"/></label>{loading?<p className="mm-admin-empty">Loading messages…</p>:!filtered.length?<p className="mm-admin-empty">No conversations found.</p>:filtered.map(t=><button key={t.id} aria-pressed={selected?.id===t.id} disabled={busy} onClick={()=>setSelected(t)}><span className="mm-avatar">{t.name?.slice(0,1)||'C'}</span><span><strong>{t.name}</strong><small>{clientText(t.lastMessage?.preview||t.detailedService)}</small></span><span aria-hidden="true">↗</span></button>)}</aside>
 <section className="mm-conversation">{!selected?<div className="mm-admin-empty"><p className="mm-eyebrow">ONE CONVERSATION AT A TIME</p><h2>A personal touch.</h2><p>Select a client to read their request and reply.</p></div>:<>
 <header><button className="mm-inbox-back" onClick={()=>setSelected(null)}>← All messages</button><div><h2>{selected.name}</h2><p>{selected.detailedService||selected.serviceCategory}</p></div><Status value={selected.status}/><button className="mm-text-link" onClick={()=>onOpenFullQuote(selected)}>Client details ↗</button></header>
 <div className="mm-message-list" aria-live="polite">{messageLoading?<p>Loading conversation…</p>:messages.length?messages.map(m=><article key={m.id} className={'mm-message '+(m.sender==='admin'?'is-studio':'')}><small>{m.sender==='admin'?'The Makeover Mommy':selected.name} / {new Date(m.createdAt).toLocaleDateString()}</small><p>{clientText(m.message)}</p>{m.isQuote&&<strong>Estimate: {m.quotePrice}</strong>}</article>):<p>No messages yet. Start a conversation with this client.</p>}</div>
 <form className="mm-reply" onSubmit={send}><label>Reply to {selected.name}<textarea required value={reply} onChange={e=>setReply(e.target.value)} rows={3} maxLength={5000} placeholder="Write a thoughtful reply…"/></label><div><label className="mm-checkbox"><input type="checkbox" checked={attach} onChange={e=>setAttach(e.target.checked)}/>Include an estimate</label>{attach&&<label>Estimate (USD)<input type="number" min="0" step=".01" required value={price} onChange={e=>setPrice(e.target.value)}/></label>}<button className="mm-button" disabled={busy||messageLoading}>{busy?'Sending…':'Send reply ↗'}</button></div></form>
 </>}</section></div>{error&&<div className="mm-error" role="alert">{error} <button onClick={()=>setReload(n=>n+1)}>Retry</button></div>}</>;
}
