import React, { useState, useRef } from 'react';
import { quotesApi } from '../../services/api';
import { SERVICES, SERVICE_CATEGORIES } from '../../data/servicesData';
import useDialog from '../../hooks/useDialog';
export default function NewOrderModal({isOpen,onClose,onCreated}){
 const ref=useRef(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',email:'',phone:'',serviceCategory:'Eyebrows',detailedService:'',details:'',timeline:'Flexible / next available'});
 useDialog(ref,onClose,isOpen);
 if(!isOpen)return null;
 const change=e=>setForm(f=>({...f,[e.target.name]:e.target.value,...(e.target.name==='serviceCategory'?{detailedService:''}:{})}));
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await quotesApi.submitPublicQuote({...form,id:'MM-'+crypto.randomUUID(),make:'PMU Consultation',modelAndYear:'',detailedService:form.detailedService||'Consultation'});if(!r.success||!r.quote)throw new Error();onCreated(r.quote);}catch{setError('The consultation could not be saved. Please try again.');}finally{setBusy(false);}};
 return <div className="mm-modal-backdrop" data-lenis-prevent><section className="mm-booking mm-admin-dialog" ref={ref} role="dialog" aria-modal="true" aria-labelledby="new-consultation-title"><header><span className="mm-eyebrow">CLIENT CARE / NEW RECORD</span><button onClick={onClose}>Close</button></header><form className="mm-booking-body mm-fields" onSubmit={submit}><h2 id="new-consultation-title">A new connection.</h2><p>Record a walk-in or phone consultation.</p><label>Client name<input name="name" required value={form.name} onChange={change}/></label><div className="mm-field-pair"><label>Email<input name="email" type="email" required value={form.email} onChange={change}/></label><label>Phone<input name="phone" type="tel" value={form.phone} onChange={change}/></label></div><label>Category<select name="serviceCategory" value={form.serviceCategory} onChange={change}>{SERVICE_CATEGORIES.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>Treatment<select name="detailedService" value={form.detailedService} onChange={change}><option value="">General consultation</option>{SERVICES.filter(s=>s.category===form.serviceCategory).map(s=><option key={s.id}>{s.title}</option>)}</select></label><label>Notes<textarea name="details" rows={3} value={form.details} onChange={change}/></label>{error&&<p className="mm-error" role="alert">{error}</p>}<footer className="mm-booking-controls"><button type="button" className="mm-text-link" onClick={onClose}>Cancel</button><button className="mm-button" disabled={busy}>{busy?'Saving…':'Create consultation ↗'}</button></footer></form></section></div>;
}
