import React, { useState, useRef } from 'react';
import { quotesApi } from '../../services/api';
import useDialog from '../../hooks/useDialog';
export default function QuoteDetailModal({quote,onClose,onUpdate}){
 const ref=useRef(null),[tab,setTab]=useState('details'),[status,setStatus]=useState(quote.status||'pending'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [estimate,setEstimate]=useState({price:quote.quotedPrice||'',turnaround:quote.estimatedTurnaround||'',warranty:quote.warrantyNote||'',message:quote.adminMessage||('Hi '+quote.name+', thank you for reaching out to The Makeover Mommy. Here are the details for your treatment. Please contact the studio to confirm your visit.')});
 useDialog(ref,onClose);
 const act=async task=>{setBusy(true);setError('');setNotice('');try{await task();}catch(e){setError(e.message||'The change could not be saved.');}finally{setBusy(false);}};
 const send=e=>{e.preventDefault();act(async()=>{const r=await quotesApi.sendQuote(quote.id,estimate);if(!r.success)throw new Error('The estimate could not be sent.');setNotice(!r.emailDelivery?.success?'Estimate saved. Email delivery is unavailable; contact the client directly.':'Estimate sent to the client.');setStatus('quoted');if(r.quote)onUpdate(r.quote);});};
 return <div className="mm-modal-backdrop" data-lenis-prevent><section ref={ref} className="mm-booking mm-admin-dialog" role="dialog" aria-modal="true" aria-labelledby="client-detail-title"><header><span className="mm-eyebrow">CLIENT CONSULTATION</span><button onClick={onClose}>Close</button></header><div className="mm-booking-body"><h2 id="client-detail-title">{quote.name}</h2><p className="mm-muted">{quote.detailedService||quote.serviceCategory}</p><div className="mm-client-contact"><a href={'mailto:'+quote.email}>{quote.email}</a>{quote.phone&&<a href={'tel:'+quote.phone.replace(/[^0-9+]/g,'')}>{quote.phone}</a>}</div><label className="mm-client-status">Consultation status<select disabled={busy} value={status} onChange={e=>{const value=e.target.value;act(async()=>{const updated=await quotesApi.updateStatus(quote.id,value);setStatus(value);onUpdate(updated);setNotice('Status updated.');});}}>{[['pending','Awaiting review'],['in_review','In review'],['quoted','Estimate sent'],['completed','Completed'],['archived','Archived']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><div className="mm-tabs"><button aria-pressed={tab==='details'} onClick={()=>setTab('details')}>Client request</button><button aria-pressed={tab==='estimate'} onClick={()=>setTab('estimate')}>Prepare an estimate</button></div>{error&&<p className="mm-error" role="alert">{error}</p>}{notice&&<p className="mm-success" role="status">{notice}</p>}
 {tab==='details'?<div className="mm-client-details"><dl><dt>Treatment</dt><dd>{quote.detailedService||quote.serviceCategory}</dd><dt>Preferred timing</dt><dd>{quote.timeline||'Flexible'} {quote.specificDate||''}</dd><dt>Received</dt><dd>{new Date(quote.createdAt).toLocaleString()}</dd><dt>Reference</dt><dd>{quote.id}</dd></dl><h3>Client notes</h3><p>{quote.details||quote.additionalNotes||'No additional notes.'}</p><button className="mm-delete" disabled={busy} onClick={()=>{if(window.confirm('Permanently delete this consultation? This cannot be undone.'))act(async()=>{await quotesApi.deleteQuote(quote.id);onUpdate({...quote,_deleted:true});onClose();});}}>Delete consultation</button></div>:<form className="mm-fields" onSubmit={send}><div className="mm-field-pair"><label>Estimate (USD)<input type="number" min="0" step=".01" required value={estimate.price} onChange={e=>setEstimate(s=>({...s,price:e.target.value}))}/></label><label>Estimated duration<input value={estimate.turnaround} onChange={e=>setEstimate(s=>({...s,turnaround:e.target.value}))}/></label></div><label>Aftercare or service note<input value={estimate.warranty} onChange={e=>setEstimate(s=>({...s,warranty:e.target.value}))}/></label><label>Personal message<textarea rows={5} required value={estimate.message} onChange={e=>setEstimate(s=>({...s,message:e.target.value}))}/></label><p className="mm-muted">Sends the estimate to the client's email through your configured studio email service.</p><button className="mm-button" disabled={busy}>{busy?'Sending…':'Send estimate ↗'}</button></form>}
 </div></section></div>;
}
