import React,{useState,useEffect} from 'react';
import {SERVICES} from '../data/servicesData';
import {BUSINESS_INFO as B} from '../data/businessData';
const short=[
 'Fine hair-like strokes for softly defined, natural-looking brows.',
 'A shaded, powder-soft brow with a gentle gradient.',
 'Hair-like strokes meet soft shading for a fuller brow.',
 'Subtle brow definition designed around your natural hair pattern.',
 'A sheer wash of colour, blended to complement your lips.',
 'A more defined, full-colour finish for your lips.',
 'Delicate definition along your natural lip border.',
 'Subtle pigment through the lash line for added definition.',
 'Classic liner or a softly tailored wing, designed around your eyes.',
 'Restorative 3D areola tattooing. Complimentary for breast cancer survivors.',
 'A personal consultation to explore skin-tone scar camouflage.',
 'A consultation-led microneedling treatment for skin texture.',
 'Makeup artistry for your wedding, event, or special occasion.'
];
const Link=({to,children,...rest})=><a href={'#/'+to} onClick={()=>{if(!to)window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}} {...rest}>{children}</a>;
const Label=({children})=><p className="mm-kicker">{children}</p>;
const Book=({onBook,children='Let’s talk about you',service='',className=''})=><button className={'mm-cta '+className} onClick={()=>onBook(service)}>{children}<span aria-hidden="true">↗</span></button>;
function Header({page,onBook}){const [open,setOpen]=useState(false);useEffect(()=>setOpen(false),[page]);return <header className="mm-header"><Link to="" className="mm-wordmark" aria-label="The Makeover Mommy home">the makeover<br/><b>mommy.</b></Link><nav aria-label="Main navigation" className={open?'is-open':''}>{[['procedures','The treatments'],['studio','Meet Porsche'],['pledge','The survivor pledge']].map(([p,l])=><Link key={p} to={p} aria-current={page===p?'page':undefined}>{l}</Link>)}<a href="#location" onClick={e=>{e.preventDefault();setOpen(false);document.getElementById("location")?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"});}}>Visit us</a></nav><Book onBook={onBook}>Book a consultation</Book><button className="mm-menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Close':'Menu'}</button></header>;}
function Stack({onBook}){return <section className="mm-section mm-treatments" id="procedures"><div className="mm-section-head"><div><Label>A LITTLE DEFINITION. A BIG DIFFERENCE.</Label><h2>Less routine.<br/>More <em>you.</em></h2></div><p>Thoughtful enhancements, designed around your features. Find your starting point.</p></div><div className="mm-stack">{[
 ['01','Your brows, reimagined.','From feather-light strokes to a soft powder finish. A shape that feels like yours.','Eyebrows','/images/natural-beauty.jpg','Portrait illustrating natural beauty'],
 ['02','A little colour. A lot of ease.','Lip blush and lash-line definition for an effortlessly put-together feeling.','Lips','/images/lip-blush.jpg','Lip colour inspiration'],
 ['03','Care that goes deeper.','Restorative tattooing and scar camouflage, with space for your story.','Paramedical','/images/hero-porsche.jpg','Tattoo artist at work']
 ].map(([n,title,desc,cat,img,alt],i)=><article key={n} className={'mm-stack-card mm-stack-'+i} style={{'--index':i}}><div><Label>{n} / {cat.toUpperCase()}</Label><h3>{title}</h3><p>{desc}</p><Link className="mm-cta mm-outline" to={'procedures?category='+cat}>Explore {cat==='Paramedical'?'restorative care':cat.toLowerCase()}<span aria-hidden="true">↗</span></Link></div><img src={img} alt={alt} loading="lazy"/></article>)}</div><Link className="mm-text-link" to="procedures">View the complete treatment menu <span aria-hidden="true">↗</span></Link></section>;}
function Home({onBook}){return <><section className="mm-hero"><div className="mm-hero-copy"><Label>PERMANENT MAKEUP & RESTORATIVE ARTISTRY / FOLSOM, CA</Label><h1>Beauty.<br/>On your<br/><em>terms.</em></h1><div className="mm-hero-bottom"><p>Soft definition. A simpler morning.<br/>Beautifully, unmistakably you.</p><Book onBook={onBook}>Find your treatment</Book></div></div><div className="mm-hero-image"><img src="/images/natural-beauty.jpg" alt="Natural beauty portrait" fetchPriority="high"/><span className="mm-image-caption">THE MAKEOVER MOMMY / BEAUTY, PERSONALLY</span><div className="mm-hero-stamp">Made for<br/><em>real life.</em></div></div></section><div className="mm-ticker" aria-label="Brows, lips, eyes and restorative artistry"><span>BROWS</span><span>—</span><span>LIPS</span><span>—</span><span>EYES</span><span>—</span><span>RESTORATIVE ARTISTRY</span></div><Stack onBook={onBook}/><section className="mm-meet mm-section"><div className="mm-meet-image"><img src="/images/hero-porsche.jpg" alt="Tattoo artistry at The Makeover Mommy" loading="lazy"/><span>THE ARTIST / PORSCHE RAY</span></div><div><Label>GOOD HANDS. A PERSONAL TOUCH.</Label><h2>Precision is an art.<br/><em>So is listening.</em></h2><p>Meet Porsche Ray. An 18x certified permanent makeup artist who makes room for your features, your comfort, and your story.</p><Link to="studio" className="mm-text-link">Get to know Porsche <span aria-hidden="true">↗</span></Link></div></section><section className="mm-pledge-teaser mm-section"><Label>THE SURVIVOR PLEDGE</Label><h2>A little artistry.<br/><em>A meaningful new chapter.</em></h2><div><p>Complimentary 3D areola restoration for breast cancer survivors. A personal commitment, made with care.</p><Link className="mm-cta mm-light" to="pledge">Discover the pledge <span aria-hidden="true">↗</span></Link></div></section></>;}
function Treatments({onBook}){const getCategory=()=>new URLSearchParams(location.hash.split('?')[1]).get('category')||'All';const [category,setCategory]=useState(getCategory),[search,setSearch]=useState('');useEffect(()=>{const sync=()=>{setCategory(getCategory());setSearch('');};window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);const cats=['All',...new Set(SERVICES.map(s=>s.category))];const services=SERVICES.filter(s=>(category==='All'||s.category===category)&&(s.title+' '+s.category).toLowerCase().includes(search.toLowerCase()));return <div className="mm-section mm-menu-page"><Label>THE TREATMENT EDIT / 01</Label><div className="mm-section-head"><h1>Small details.<br/><em>Beautiful impact.</em></h1><p>Explore the possibilities. Your consultation is where we find what’s right for you.</p></div><div className="mm-filter"><div aria-label="Filter treatments">{cats.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="mm-search"><span className="sr-only">Search treatments</span><input type="search" placeholder="Find your treatment" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><p className="mm-result-count" aria-live="polite">{services.length} treatments / select one to explore</p><div className="mm-service-list">{services.map(s=><details key={s.id}><summary><span className="mm-service-number">{String(SERVICES.indexOf(s)+1).padStart(2,'0')}</span><span><small>{s.category}</small><h2>{s.title}</h2></span><span className="mm-duration">{s.duration}</span><span className="mm-plus" aria-hidden="true">+</span></summary><div className="mm-service-body"><p>{short[SERVICES.indexOf(s)]}</p><div><p><span>TECHNIQUE</span>{s.subType}</p><p><span>APPOINTMENT LENGTH</span>{s.duration}</p><small>Suitability, healing, and results are discussed during your consultation.</small></div><Book onBook={onBook} service={s.title}>Ask about this treatment</Book></div></details>)}</div>{!services.length&&<p className="mm-empty">No treatments match. Try a different search or category.</p>}<div className="mm-help"><div><h2>Not sure where to start?</h2><p>That’s what a conversation is for.</p></div><Book onBook={onBook}>Ask Porsche</Book></div></div>;}
function Studio({onBook}){return <><section className="mm-section mm-studio-hero"><div><Label>THE ARTIST / 02</Label><h1>Artistry.<br/>Intention.<br/><em>Porsche.</em></h1><p>Considered enhancements that leave you feeling more like yourself.</p><Book onBook={onBook}>Meet for a consultation</Book></div><img src="/images/hero-porsche.jpg" alt="Tattoo artist working carefully with a client"/></section><section className="mm-section mm-story"><Label>PORSCHE RAY / FOUNDER & PMU ARTIST</Label><div><h2>A personal approach<br/>to <em>permanent beauty.</em></h2><p>Porsche brings 18 advanced certifications and a careful eye to permanent cosmetics and paramedical tattooing. Every appointment begins with a conversation about what you want to feel when you look in the mirror.</p><p>From a softly defined brow to restorative areola artistry, her work balances considered detail with compassionate care. Find her inside Motsy Beauty Lounge in Folsom.</p></div></section><section className="mm-section mm-process"><Label>YOUR TIME WITH US</Label><div>{[['01','We listen.','Your goals, questions, and comfort come first.'],['02','We design.','Shape, placement, and colour are discussed together.'],['03','We care.','Leave with clear aftercare guidance and your next steps.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section><section className="mm-section mm-review"><Label>IN A CLIENT’S WORDS</Label><blockquote>“They look so natural that my coworkers thought I was just blessed with great genetics.”</blockquote><p>Jessica T. / Folsom</p><details><summary>More client stories +</summary>{B.reviews.slice(1).map(r=><article key={r.author}><p>“{r.comment}”</p><small>{r.author} / {r.location}</small></article>)}</details></section></>;}
function Pledge({onBook}){const service=SERVICES.find(s=>s.category==='Paramedical');return <><section className="mm-section mm-pledge-page"><Label>THE SURVIVOR PLEDGE / 03</Label><h1>Your story.<br/>Your pace.<br/><em>Our care.</em></h1><p className="mm-lead">Complimentary 3D areola restoration for breast cancer survivors.</p><Book className="mm-light" onBook={onBook} service={service.title}>Start a private conversation</Book><span className="mm-pledge-note">WITH PORSCHE RAY / FOLSOM, CALIFORNIA</span></section><section className="mm-section mm-story"><Label>A COMMITMENT FROM THE HEART</Label><div><h2>Space for your<br/><em>next chapter.</em></h2><p>Restorative artistry is deeply personal. Porsche offers 3D areola tattooing at no charge to breast cancer survivors, with care and attention throughout the process.</p><p>The studio’s pledge is for survivors healed for at least six months after surgery. A private consultation is the first step to discussing timing and individual suitability.</p><p>You don’t need to share your medical history in the enquiry form. We’ll begin with a conversation.</p><a className="mm-text-link" href="tel:9165428801">Speak directly with the studio ↗</a></div></section></>;}
function Footer({onBook}){return <footer id="location" className="mm-footer"><div className="mm-footer-top"><div><Label>YOUR NEXT CHAPTER STARTS HERE.</Label><h2>Make a little<br/><em>time for you.</em></h2><Book className="mm-light" onBook={onBook}>Book a consultation</Book></div><div className="mm-visit"><Label>COME AS YOU ARE.</Label><p>Motsy Beauty Lounge<br/>6693 Folsom-Auburn Road, Suite E<br/>Folsom, CA 95630</p><a href={B.googleMapsLink} target="_blank" rel="noreferrer">Get directions ↗</a><a href="tel:9165428801">(916) 542-8801</a><a href={'mailto:'+B.email}>{B.email}</a><p className="mm-hours">Tuesday–Friday / 9am–6pm<br/>Saturday / 9am–4pm, by appointment<br/>Sunday & Monday / closed</p><details><summary>Appointment policy +</summary><p>{B.cancellationPolicy}</p></details></div></div><div className="mm-footer-wordmark">the makeover mommy.</div><div className="mm-footer-bottom"><span>© {new Date().getFullYear()} The Makeover Mommy LLC</span><Link to="admin">Studio access ↗</Link><Link to="">Back to the beginning ↑</Link></div></footer>;}
export default function Website({page,onBook}){useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('mm-visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.mm-section-head,.mm-meet,.mm-story,.mm-process,.mm-review').forEach(el=>{el.classList.add('mm-reveal');observer.observe(el);});return()=>observer.disconnect();},[page]);return <div className="mm-site"><a href="#main" className="mm-skip" onClick={e=>{e.preventDefault();document.getElementById("main")?.focus();}}>Skip to content</a><Header page={page} onBook={onBook}/><main id="main" tabIndex={-1} key={page}>{page==='procedures'?<Treatments onBook={onBook}/>:page==='studio'?<Studio onBook={onBook}/>:page==='pledge'?<Pledge onBook={onBook}/>:<Home onBook={onBook}/>}</main><Footer onBook={onBook}/></div>;}
